//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadText.LocalizedDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReadText.LocalizedDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  bytes.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal scenario.
        /// </summary>
        public static string ExamplesNormalScenario {
            get {
                return ResourceManager.GetString("ExamplesNormalScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read more lines.
        /// </summary>
        public static string ExamplesReadMoreLines {
            get {
                return ResourceManager.GetString("ExamplesReadMoreLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify bytes.
        /// </summary>
        public static string ExamplesSpecifyBytes {
            get {
                return ResourceManager.GetString("ExamplesSpecifyBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suppress summary.
        /// </summary>
        public static string ExamplesSuppressSummary {
            get {
                return ResourceManager.GetString("ExamplesSuppressSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from bottom:.
        /// </summary>
        public static string FromBottom {
            get {
                return ResourceManager.GetString("FromBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from top:.
        /// </summary>
        public static string FromTop {
            get {
                return ResourceManager.GetString("FromTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes to be printed from the beginning or end of the file..
        /// </summary>
        public static string HelpTextBytes {
            get {
                return ResourceManager.GetString("HelpTextBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file to be processed..
        /// </summary>
        public static string HelpTextFileName {
            get {
                return ResourceManager.GetString("HelpTextFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines to be printed from the beginning or end of the file..
        /// </summary>
        public static string HelpTextLines {
            get {
                return ResourceManager.GetString("HelpTextLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppresses summary messages..
        /// </summary>
        public static string HelpTextQuiet {
            get {
                return ResourceManager.GetString("HelpTextQuiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays first lines of a file..
        /// </summary>
        public static string HelpTextVerbHead {
            get {
                return ResourceManager.GetString("HelpTextVerbHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays last lines of a file..
        /// </summary>
        public static string HelpTextVerbTail {
            get {
                return ResourceManager.GetString("HelpTextVerbTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  lines.
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading .
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Možnost &apos;{0}&apos; je definována ve špatném formátu..
        /// </summary>
        public static string SentenceBadFormatConversionErrorOption {
            get {
                return ResourceManager.GetString("SentenceBadFormatConversionErrorOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value not bound to option name is defined with a bad format..
        /// </summary>
        public static string SentenceBadFormatConversionErrorValue {
            get {
                return ResourceManager.GetString("SentenceBadFormatConversionErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token &apos;{0}&apos; is not recognized..
        /// </summary>
        public static string SentenceBadFormatTokenError {
            get {
                return ResourceManager.GetString("SentenceBadFormatTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verb &apos;{0}&apos; is not recognized..
        /// </summary>
        public static string SentenceBadVerbSelectedError {
            get {
                return ResourceManager.GetString("SentenceBadVerbSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR(S):.
        /// </summary>
        public static string SentenceErrorsHeadingText {
            get {
                return ResourceManager.GetString("SentenceErrorsHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this help screen..
        /// </summary>
        public static string SentenceHelpCommandTextOption {
            get {
                return ResourceManager.GetString("SentenceHelpCommandTextOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display more information on a specific command..
        /// </summary>
        public static string SentenceHelpCommandTextVerb {
            get {
                return ResourceManager.GetString("SentenceHelpCommandTextVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required option &apos;{0}&apos; is missing..
        /// </summary>
        public static string SentenceMissingRequiredOptionError {
            get {
                return ResourceManager.GetString("SentenceMissingRequiredOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required value not bound to option name is missing..
        /// </summary>
        public static string SentenceMissingRequiredValueError {
            get {
                return ResourceManager.GetString("SentenceMissingRequiredValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; has no value..
        /// </summary>
        public static string SentenceMissingValueOptionError {
            get {
                return ResourceManager.GetString("SentenceMissingValueOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options: {0} are not compatible with {1}..
        /// </summary>
        public static string SentenceMutuallyExclusiveSetErrors {
            get {
                return ResourceManager.GetString("SentenceMutuallyExclusiveSetErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No verb selected..
        /// </summary>
        public static string SentenceNoVerbSelectedError {
            get {
                return ResourceManager.GetString("SentenceNoVerbSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is defined multiple times..
        /// </summary>
        public static string SentenceRepeatedOptionError {
            get {
                return ResourceManager.GetString("SentenceRepeatedOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required..
        /// </summary>
        public static string SentenceRequiredWord {
            get {
                return ResourceManager.GetString("SentenceRequiredWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence option &apos;{0}&apos; is defined with fewer or more items than required..
        /// </summary>
        public static string SentenceSequenceOutOfRangeErrorOption {
            get {
                return ResourceManager.GetString("SentenceSequenceOutOfRangeErrorOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence value not bound to option name is defined with fewer items than required..
        /// </summary>
        public static string SentenceSequenceOutOfRangeErrorValue {
            get {
                return ResourceManager.GetString("SentenceSequenceOutOfRangeErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting value to option &apos;{0}&apos;: {1}.
        /// </summary>
        public static string SentenceSetValueExceptionError {
            get {
                return ResourceManager.GetString("SentenceSetValueExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is unknown..
        /// </summary>
        public static string SentenceUnknownOptionError {
            get {
                return ResourceManager.GetString("SentenceUnknownOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE:.
        /// </summary>
        public static string SentenceUsageHeadingText {
            get {
                return ResourceManager.GetString("SentenceUsageHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display version information..
        /// </summary>
        public static string SentenceVersionCommandText {
            get {
                return ResourceManager.GetString("SentenceVersionCommandText", resourceCulture);
            }
        }
    }
}
