//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/gsscoder/invariantstrtool.
//     Version: 1.0.0.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandLine.Internal
{
    internal static class SR
    {
        public const string ArgumentNullException_ArgsStringArrayCannotBeNull = "The arguments string array cannot be null.";
        public const string ArgumentNullException_OptionsInstanceCannotBeNull = "The target options instance cannot be null.";
        public const string ArgumentNullException_CommandLineParserSettingsInstanceCannotBeNull = "The command line parser settings instance cannot be null.";
        public const string ArgumentNullException_AttributeCannotBeNull = "The attribute is mandatory.";
        public const string ArgumentNullException_PropertyCannotBeNull = "The property is mandatory.";
        public const string CommandLineParserException_CannotCreateInstanceForVerbCommand = "Instance defined for verb command could not be created.";
    }
}
